---
# tasks file for node-exporter
    - name: unarchive node exporter 
      ansible.builtin.unarchive:
       src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
       dest: /home/ubuntu
       remote_src: yes

    - name: copy file from node exporter for service 
      ansible.builtin.copy:
       src: /home/ubuntu/node_exporter-1.3.1.linux-amd64/.
       dest: /usr/local/bin/node
       remote_src: yes
      become: yes

    - name: copy service file  
      ansible.builtin.copy:
       src: /home/ubuntu/ansible/servicefiles/node-service
       dest: /etc/systemd/system/node.service
      become: yes

    - name: start node exporter service
      ansible.builtin.service:
        name: node
        state: started
