---
- hosts: localhost
  become: no
#  become_pass: addweb123 
  gather_facts: false

  tasks: 
    - name: download prometheus
      get_url:
       url: https://github.com/prometheus/prometheus/releases/download/v2.33.3/prometheus-2.33.3.linux-amd64.tar.gz
       dest: /home/ubuntu
 
    - name: unarchive prometheus file 
      ansible.builtin.unarchive:
       src: /home/ubuntu/prometheus-2.33.3.linux-amd64.tar.gz
       dest: /home/ubuntu

    - name: copy file from prometheus for service 
      ansible.builtin.copy:
       src: /home/ubuntu/prometheus-2.33.3.linux-amd64/.
       dest: /usr/local/bin/prometheus
      become: yes

    - name: copy service file  
      ansible.builtin.copy:
       src: /home/ubuntu/ansible/service
       dest: /etc/systemd/system/prometheus.service
      become: yes


    - name: start prometheus service
      ansible.builtin.service:
        name: prometheus
        state: started
