---
- hosts: ubuntu
  become: no
  gather_facts: false

  roles:
      - prometheus
      
  #   - name: copy file from prometheus for service 
  #     ansible.builtin.copy:
  #      src: /home/ubuntu/prometheus-2.33.3.linux-amd64/./
  #      dest: /usr/local/bin/prometheus
  #     become: yes

  #   - name: chnage permission
  #     ansible.builtin.file:
  #      path: /usr/local/bin/prometheus/prometheus
  #      mode: '0755'
  #     become: yes

  #   - name: copy service file  
  #     ansible.builtin.copy:
  #      src: /home/ubuntu/ansible/servicefiles/prometheus-service
  #      dest: /etc/systemd/system/prometheus.service
  #     become: yes


  #   - name: start prometheus service
  #     ansible.builtin.service:
  #       name: prometheus
  #       state: started


  #  # - name: copy script 
  #  #   shell: /home/ubuntu/ansible/jon.sh

  #  ######################################NODE-EXPORTER############################


  #  # - name: download node 
  #  #   get_url:
  #  #    url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
  #  #    dest: /home/ubuntu
 
  #   - name: unarchive node exporter 
  #     ansible.builtin.unarchive:
  #      src: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
  #      dest: /home/ubuntu
  #      remote_src: yes

  #   - name: copy file from node exporter for service 
  #     ansible.builtin.copy:
  #      src: /home/ubuntu/node_exporter-1.3.1.linux-amd64/.
  #      dest: /usr/local/bin/node
  #      remote_src: yes
  #     become: yes

  #   - name: copy service file  
  #     ansible.builtin.copy:
  #      src: /home/ubuntu/ansible/servicefiles/node-service
  #      dest: /etc/systemd/system/node.service
  #     become: yes


  #   - name: start node exporter service
  #     ansible.builtin.service:
  #       name: node
  #       state: started

     
