---
- hosts: ubuntu
  become: no
  gather_facts: false

  vars_prompt:
    - name: "Version"
      prompt: "Enter your remote server ip?"
      private: no

  roles:
     - prometheus
     - node-exporter
     - grafana
     - blackbox_exporter





     
