name: publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Install vsce
        run: npm i -g vsce

      - name: Publish to VS Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
      
      - name: Publish to Open VSX Registry
        run: npx ovsx publish -p ${{ secrets.OVSX_PAT }}
